var supplyProducts = ["Dental Hygenists", "Registered Nurses", "APRNs", "Dentists", "Emergency Room Nurses", "Brain Surgeons", "General Practicioners", "Anestheiologists", "Pharmacists", "Office Assistants"]
supplyProducts.sort()

var demandProducts = ["Nurse Practicioner", "Dentist", "Dental Hygienist", "APRN"]
demandProducts.sort()

var bizLocation = ["All US", "NewYork", "Texas", "Washington State", "Washington D.C.", "Maryland", "Florida"]
bizLocation.sort()

var bizDuration = ["1-2 Weeks", "2-4 Weeks", "1-3 Months", "3-6 Months", "6+ Months", "Permanent"]

var presentPostings = [
	{
	Specialty: "Dentists",
	SpecialtyBreakdown: "Dentist--Implant", 
	Location: "Texas",
	Duration: "1-2 Weeks", 
	Flexible: "Yes",
	DiscloseClientName: "Yes",
	Client: "MD Anderson--Houston Center", 
	ClientContact: "conrad.crassierer@mdanderson.com", 
	Date: "March 15, 2016 - March 30, 2016", 
	Experience: "5 Years", 
	Qualifications: "DDS or DMD (Degrees or Certifications)", 
	Rates: "130 per hour", 
	NonLocalHousingAndPerDiem: "Yes; 250 per Day Limit",
	InsuranceRequirements: "Malpractice--Hospital Covered",
	InsuranceAccepted: "Aetna, Blue Cross, Oscar" 
	}
]

var jobInventory = [
	{
		product: "APRN",
		productSpecialty: "APRN for Daytime Emergency Room",
		degreeRequired: "APRN",
		desiredPriorExperience: "5",
		clientName: "Sharon Hospital",
		clientSerialNumber: "Xyz1231kljlkasjdfsdaf",
		clientDefaultEmail: "whong@outlook.com",
		clientPhoneNumber: "347-610-7626",
		hideClientName: "No",
		locationCounty: "Millbrook",
		locationState: "NY",
		facilityDesc: "Sharon hospital has been serving Dutchess county since 1920",
		workDays: "10",
		weeklyHours: "40",
		totalHours: "80",
		regularRate: "80",
		payOvertime: "Yes",
		overtimeRate: "120",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "No",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Daytime only"
	},
	{
		product: "APRN",
		productSpecialty: "APRN--Summertime only",
		degreeRequired: "APRN",
		desiredPriorExperience: "2",
		clientName: "Nantucket Regional Hospital",
		clientSerialNumber: "Xyz1231kljlkasjdfsdaf",
		clientDefaultEmail: "whong@outlook.com",
		clientPhoneNumber: "347-610-7626",
		hideClientName: "No",
		locationCounty: "Nantucket",
		locationState: "MA",
		facilityDesc: "Nantucket hospital operates only during the summer providing elite healthcare to the summer community members",
		workDays: "10",
		weeklyHours: "40",
		totalHours: "80",
		regularRate: "80",
		payOvertime: "Yes",
		overtimeRate: "120",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "May 1, 2017",
		endDate: "May 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "No",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "APRN",
		productSpecialty: "APRN--Mental Health Assitance",
		degreeRequired: "APRN",
		desiredPriorExperience: "5",
		clientName: "New York State Psychiatric Institution",
		clientSerialNumber: "Xyz1231kljlkasjdfsdaf",
		clientDefaultEmail: "whong@outlook.com",
		clientPhoneNumber: "347-610-7626",
		hideClientName: "No",
		locationCounty: "Yonkers",
		locationState: "NY",
		facilityDesc: "NYS psychiatric institution enables rehabiliation of individuals who are emotionally challenged.",
		workDays: "10",
		weeklyHours: "40",
		totalHours: "80",
		regularRate: "80",
		payOvertime: "Yes",
		overtimeRate: "120",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "November 1, 2017",
		endDate: "November 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "No",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "Nurse Practicioner",
		productSpecialty: "Nurse Practicioner, Psychiatry",
		degreeRequired: "NP",
		desiredPriorExperience: "5",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "We assist NYU students and faculty members to overcome psychiatric challenges and contribute to the healthier community",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "1000",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "Nurse Practicioner",
		productSpecialty: "Nurse Practicioner, Psychiatry",
		degreeRequired: "NP",
		desiredPriorExperience: "5",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "We assist NYU students and faculty members to overcome psychiatric challenges and contribute to the healthier community",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "1000",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "Nurse Practicioner",
		productSpecialty: "Nurse Practicioner, Psychiatry",
		degreeRequired: "NP",
		desiredPriorExperience: "5",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "We assist NYU students and faculty members to overcome psychiatric challenges and contribute to the healthier community",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "1000",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "Nurse Practicioner",
		productSpecialty: "Nurse Practicioner, Psychiatry",
		degreeRequired: "NP",
		desiredPriorExperience: "5",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "We assist NYU students and faculty members to overcome psychiatric challenges and contribute to the healthier community",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "1000",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	}
]

var cliniciansInventory = []
