var supplyProducts = ["Dental Hygenists", "Registered Nurses", "APRNs", "Dentists", "Emergency Room Nurses", "Brain Surgeons", "General Practicioners", "Anestheiologists", "Pharmacists", "Office Assistants"]
supplyProducts.sort()

var demandProducts = ["Nurse Practicioner", "Dentist", "Dental Hygienist", "APRN"]
demandProducts.sort()

var bizLocation = ["All US", "NewYork", "Texas", "Washington State", "Washington D.C.", "Maryland", "Florida"]
bizLocation.sort()

var bizDuration = ["1-2 Weeks", "2-4 Weeks", "1-3 Months", "3-6 Months", "6+ Months", "Permanent"]

var presentPostings = [
	{
	Specialty: "Dentists",
	SpecialtyBreakdown: "Dentist--Implant", 
	Location: "Texas",
	Duration: "1-2 Weeks", 
	Flexible: "Yes",
	DiscloseClientName: "Yes",
	Client: "MD Anderson--Houston Center", 
	ClientContact: "conrad.crassierer@mdanderson.com", 
	Date: "March 15, 2016 - March 30, 2016", 
	Experience: "5 Years", 
	Qualifications: "DDS or DMD (Degrees or Certifications)", 
	Rates: "130 per hour", 
	NonLocalHousingAndPerDiem: "Yes; 250 per Day Limit",
	InsuranceRequirements: "Malpractice--Hospital Covered",
	InsuranceAccepted: "Aetna, Blue Cross, Oscar" 
	}
]

var jobInventory = [
	{
		product: "DentalHygienist",
		productSpecialty: "Dentist--Implant",
		degreeRequired: "APRN",
		desiredPriorExperience: "5",
		clientName: "Carl Icahn Medical Center",
		clientSerialNumber: "Xyz1231kljlkasjdfsdaf",
		clientDefaultEmail: "whong@outlook.com",
		clientPhoneNumber: "347-610-7626",
		hideClientName: "No",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "A facility where Dan Ackman goes when Carl Icahn beats the shit out of him",
		workDays: "10",
		weeklyHours: "40",
		totalHours: "80",
		regularRate: "80",
		payOvertime: "Yes",
		overtimeRate: "120",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "No",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "DentalHygienist",
		productSpecialty: "Dentist--Implant",
		degreeRequired: "APRN",
		desiredPriorExperience: "5",
		clientName: "Carl Icahn Medical Center",
		clientSerialNumber: "Xyz1231kljlkasjdfsdaf",
		clientDefaultEmail: "whong@outlook.com",
		clientPhoneNumber: "347-610-7626",
		hideClientName: "No",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "A facility where Dan Ackman goes when Carl Icahn beats the shit out of him",
		workDays: "10",
		weeklyHours: "40",
		totalHours: "80",
		regularRate: "80",
		payOvertime: "Yes",
		overtimeRate: "120",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "No",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "DentalHygienist",
		productSpecialty: "Dentist--Implant",
		degreeRequired: "APRN",
		desiredPriorExperience: "5",
		clientName: "Carl Icahn Medical Center",
		clientSerialNumber: "Xyz1231kljlkasjdfsdaf",
		clientDefaultEmail: "whong@outlook.com",
		clientPhoneNumber: "347-610-7626",
		hideClientName: "No",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "A facility where Dan Ackman goes when Carl Icahn beats the shit out of him",
		workDays: "10",
		weeklyHours: "40",
		totalHours: "80",
		regularRate: "80",
		payOvertime: "Yes",
		overtimeRate: "120",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "No",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "NursePracticioner",
		productSpecialty: "Ability to perscribe Adderall every day",
		degreeRequired: "NP",
		desiredPriorExperience: "2",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "Kids come to student health center to get adderall. We pretent that they have add and perscribe it.",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "1000",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "NursePracticioner",
		productSpecialty: "Ability to perscribe Adderall every day",
		degreeRequired: "NP",
		desiredPriorExperience: "2",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "Kids come to student health center to get adderall. We pretent that they have add and perscribe it.",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "1000",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "NursePracticioner",
		productSpecialty: "Ability to perscribe Adderall every day",
		degreeRequired: "NP",
		desiredPriorExperience: "2",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "Kids come to student health center to get adderall. We pretent that they have add and perscribe it.",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "1000",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "APRN",
		productSpecialty: "Ability to perscribe Adderall every day",
		degreeRequired: "NP",
		desiredPriorExperience: "2",
		clientName: "NYU Health Center",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-7626",
		hideClientName: "Yes",
		locationCounty: "New York",
		locationState: "NY",
		facilityDesc: "Kids come to student health center to get adderall. We pretent that they have add and perscribe it.",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "200",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "APRN",
		productSpecialty: "Ability to sell stuff to people",
		degreeRequired: "MD or Equivalent",
		desiredPriorExperience: "10",
		clientName: "Won Jun Hong Clinic",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-1111",
		hideClientName: "Yes",
		locationCounty: "Birmingham",
		locationState: "AL",
		facilityDesc: "A beaututiful hospital located in deep south",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "200",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Female Only"
	},
	{
		product: "APRN",
		productSpecialty: "Separating Conjoined Twins",
		degreeRequired: "MD or Equivalent",
		desiredPriorExperience: "10",
		clientName: "Johns Hopkins Hospital",
		clientSerialNumber: "sdfljsdklfjlkwejrklqewr",
		clientDefaultEmail: "won.hong@stern.nyu.edu",
		clientPhoneNumber: "347-111-1111",
		hideClientName: "Yes",
		locationCounty: "Baltimore",
		locationState: "MD",
		facilityDesc: "Inheriting the legacy of Dr. Benjamin Carson",
		workDays: "20",
		weeklyHours: "50",
		totalHours: "200",
		regularRate: "120",
		payOvertime: "Yes",
		overtimeRate: "180",
		perDiem: "350",
		hotelReimbursement: "250",
		startDate: "March 1, 2017",
		endDate: "March 31, 2017",
		imageList: [],
		malpracticeInsruanceRequired: "Yes",
		malpracticeInsuranceAccpeted: "Aetna, Blue Cross, Oscar",
		specialNote: "Republicans Only"
	}
]

var cliniciansInventory = []
